version: 1.0.0

service:
  bind:
    address: 0.0.0.0
    port: 8080
  shutdown_timeout: 10
  jwt_ttl: 14400
  jwt_secret: D5PK[erP05Sfrtw0OV+Vb&0'2c8SSd6
  base_url: 81.163.28.182:8080/api
  scheme: http
  host: 81.163.28.182
  port: 8080

sender:
  email:
    host: smtp.gmail.com
    port: 587
    sender: "digital.attorney.mvp@gmail.com"
    user: digital.attorney.mvp@gmail.com
    password: p@ssw0rd17
    templates_dir: /templates/email
  sms:
    host_phone:
    templates_dir: /templates/sms

logging:
  level: debug

db:
  connection_string: mongodb://root:rootpassword@mongodb_container:27017
  database: digital_attorney
