version: "2"
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile

    ports:
      - "8000:8000"
    restart:
      always

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - 3000:80
    environment:
      - CHOKIDAR_USEPOLLING=true
