version: "2"
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile

    ports:
      - "8000:8000"
    restart:
      always

  frontend:
    container_name: frontend
    build: frontend/
    ports:
      - "80:80"
    environment:
      - CHOKIDAR_USEPOLLING=true
